version: '3.8'  # Use Docker Compose file version 3.8

services:
  device:
    build: device  # Build the Dockerfile in the current directory
    environment:
      - PYTHONUNBUFFERED=1
    devices:
      - "/dev/v4l/by-id/usb-USB_USB_SN0001-video-index0:/dev/video0"  # Map /dev/video0 from host to container
    restart: unless-stopped  # Restart policy to handle reboots and crashes
    volumes:
      - type: bind
        source: /etc/iot-sc/
        target: /etc/iot-sc/
      - type: bind
        source: /opt/iot-sc/
        target: /opt/iot-sc/
